import type { CdtEntry } from "./types";

export const CDT_CATALOG: readonly CdtEntry[] = [
  { code: "D0120", title: "Periodic oral evaluation", shortLabel: "Checkup", group: "exam", defaultPhase: "urgent" },
  { code: "D0140", title: "Limited oral evaluation, problem focused", shortLabel: "Problem exam", group: "exam", defaultPhase: "urgent" },
  { code: "D0150", title: "Comprehensive oral evaluation", shortLabel: "Full exam", group: "exam", defaultPhase: "urgent" },
  { code: "D9110", title: "Palliative treatment of dental pain", shortLabel: "Pain relief", group: "exam", defaultPhase: "urgent" },
  { code: "D2330", title: "Resin composite, one surface anterior", shortLabel: "Fill (front)", group: "filling", defaultPhase: "restorative" },
  { code: "D2331", title: "Resin composite, two surfaces anterior", shortLabel: "Fill (front, 2)", group: "filling", defaultPhase: "restorative" },
  { code: "D2332", title: "Resin composite, three surfaces anterior", shortLabel: "Fill (front, 3)", group: "filling", defaultPhase: "restorative" },
  { code: "D2391", title: "Resin composite, one surface posterior", shortLabel: "Fill", group: "filling", defaultPhase: "restorative" },
  { code: "D2392", title: "Resin composite, two surfaces posterior", shortLabel: "Fill (2 surfaces)", group: "filling", defaultPhase: "restorative" },
  { code: "D2393", title: "Resin composite, three surfaces posterior", shortLabel: "Fill (3 surfaces)", group: "filling", defaultPhase: "restorative" },
  { code: "D2394", title: "Resin composite, four or more surfaces posterior", shortLabel: "Fill (4 surfaces)", group: "filling", defaultPhase: "restorative" },
  { code: "D3220", title: "Therapeutic pulpotomy", shortLabel: "Pulpotomy", group: "endo", defaultPhase: "urgent" },
  { code: "D3310", title: "Endodontic therapy, anterior", shortLabel: "Root canal (front)", group: "endo", defaultPhase: "urgent" },
  { code: "D3320", title: "Endodontic therapy, premolar", shortLabel: "Root canal (premolar)", group: "endo", defaultPhase: "urgent" },
  { code: "D3330", title: "Endodontic therapy, molar", shortLabel: "Root canal", group: "endo", defaultPhase: "urgent" },
  { code: "D7140", title: "Extraction, erupted tooth", shortLabel: "Extract", group: "extract", defaultPhase: "urgent" },
  { code: "D7210", title: "Extraction, surgical", shortLabel: "Surgical extract", group: "extract", defaultPhase: "urgent" },
  { code: "D7220", title: "Removal of impacted tooth, soft tissue", shortLabel: "Impacted (soft)", group: "extract", defaultPhase: "urgent" },
  { code: "D7230", title: "Removal of impacted tooth, partially bony", shortLabel: "Impacted (bone)", group: "extract", defaultPhase: "urgent" },
  { code: "D7510", title: "Incision and drainage of abscess", shortLabel: "Drain abscess", group: "extract", defaultPhase: "urgent" },
  { code: "D2740", title: "Crown, porcelain/ceramic", shortLabel: "Crown", group: "crown", defaultPhase: "restorative" },
  { code: "D2750", title: "Crown, porcelain fused to high noble metal", shortLabel: "Crown (PFM)", group: "crown", defaultPhase: "restorative" },
  { code: "D2950", title: "Core buildup", shortLabel: "Core buildup", group: "crown", defaultPhase: "restorative" },
  { code: "D2954", title: "Prefabricated post and core", shortLabel: "Post & core", group: "crown", defaultPhase: "restorative" },
  { code: "D1110", title: "Prophylaxis, adult", shortLabel: "Cleaning", group: "perio", defaultPhase: "restorative" },
  { code: "D4341", title: "Periodontal scaling and root planing, per quadrant", shortLabel: "Scaling", group: "perio", defaultPhase: "restorative" },
  { code: "D6010", title: "Surgical placement of implant body", shortLabel: "Implant", group: "implant", defaultPhase: "prosthodontic" },
  { code: "D6058", title: "Abutment supported porcelain/ceramic crown", shortLabel: "Implant crown", group: "implant", defaultPhase: "prosthodontic" },
  { code: "D6240", title: "Pontic, porcelain fused to high noble metal", shortLabel: "Bridge pontic", group: "implant", defaultPhase: "prosthodontic" },
  { code: "D5110", title: "Complete denture, maxillary", shortLabel: "Full denture (upper)", group: "implant", defaultPhase: "prosthodontic" },
  { code: "D5213", title: "Maxillary partial denture, cast metal", shortLabel: "Partial denture", group: "implant", defaultPhase: "prosthodontic" },
  { code: "D9944", title: "Occlusal guard", shortLabel: "Night guard", group: "other", defaultPhase: "prosthodontic" },
  { code: "D9972", title: "External bleaching, per arch", shortLabel: "Whitening", group: "other", defaultPhase: "prosthodontic" },
];
