/** User-selectable via the WhatsApp theme switcher. "dark" is not offered there —
 *  it's forced automatically whenever the site-wide admin dark mode is on. */
export type WaThemePreference = "light" | "classic";
/** Effective theme actually rendered — includes "dark" once the site toggle forces it. */
export type WaThemeId = WaThemePreference | "dark";

export const WA_VAR_KEYS = [
  "--wa-header-bg",
  "--wa-header-text",
  "--wa-header-subtext",
  "--wa-header-icon",
  "--wa-header-hover",
  "--wa-header-border",
  "--wa-wallpaper-bg",
  "--wa-wallpaper-pattern",
  "--wa-bubble-in-bg",
  "--wa-bubble-in-text",
  "--wa-bubble-in-border",
  "--wa-bubble-out-bg",
  "--wa-bubble-out-text",
  "--wa-bubble-out-border",
  "--wa-bubble-meta-text",
  "--wa-tick-sent",
  "--wa-tick-read",
  "--wa-tick-failed",
  "--wa-accent",
  "--wa-composer-bg",
  "--wa-composer-border",
  "--wa-composer-field-bg",
  "--wa-composer-text",
  "--wa-composer-placeholder",
  "--wa-composer-icon",
  "--wa-composer-icon-hover-bg",
  "--wa-surface-bg",
  "--wa-surface-border",
  "--wa-surface-text",
  "--wa-surface-muted-text",
  "--wa-surface-hover",
  "--wa-highlight-bg",
  "--wa-highlight-ring",
  "--wa-reply-quote-in-border",
  "--wa-reply-quote-in-bg",
  "--wa-reply-quote-in-text",
  "--wa-reply-quote-out-border",
  "--wa-reply-quote-out-bg",
  "--wa-reply-quote-out-text",
] as const;

export type WaThemeVars = Record<(typeof WA_VAR_KEYS)[number], string>;

const LIGHT: WaThemeVars = {
  "--wa-header-bg": "#FFFFFF",
  "--wa-header-text": "#111827",
  "--wa-header-subtext": "#6B7280",
  "--wa-header-icon": "#6B7280",
  "--wa-header-hover": "#F3F4F6",
  "--wa-header-border": "#E5E7EB",
  "--wa-wallpaper-bg": "#F9FAFB",
  "--wa-wallpaper-pattern": "none",
  "--wa-bubble-in-bg": "#F3F4F6",
  "--wa-bubble-in-text": "#111827",
  "--wa-bubble-in-border": "transparent",
  "--wa-bubble-out-bg": "#FFFFFF",
  "--wa-bubble-out-text": "#111827",
  "--wa-bubble-out-border": "#E5E7EB",
  "--wa-bubble-meta-text": "#6B7280",
  "--wa-tick-sent": "#6B7280",
  "--wa-tick-read": "#53BDEB",
  "--wa-tick-failed": "#DC2626",
  "--wa-accent": "#0EA5E9",
  "--wa-composer-bg": "#F7F8FA",
  "--wa-composer-border": "#E5E7EB",
  "--wa-composer-field-bg": "#E9EDEF",
  "--wa-composer-text": "#111B21",
  "--wa-composer-placeholder": "#8696A0",
  "--wa-composer-icon": "#54656F",
  "--wa-composer-icon-hover-bg": "#E9EDEF",
  "--wa-surface-bg": "#FFFFFF",
  "--wa-surface-border": "#E5E7EB",
  "--wa-surface-text": "#111827",
  "--wa-surface-muted-text": "#6B7280",
  "--wa-surface-hover": "#F3F4F6",
  "--wa-highlight-bg": "rgba(238,242,255,0.8)",
  "--wa-highlight-ring": "rgba(99,102,241,0.4)",
  "--wa-reply-quote-in-border": "#6366F1",
  "--wa-reply-quote-in-bg": "#EEF2FF",
  "--wa-reply-quote-in-text": "#4F46E5",
  "--wa-reply-quote-out-border": "#D97706",
  "--wa-reply-quote-out-bg": "#ECFDF5",
  "--wa-reply-quote-out-text": "#B45309",
};

// Forced whenever site-wide admin dark mode is on — derived from the same
// --admin-* tokens the rest of the dark admin uses, not its own WhatsApp-
// branded palette, so the chat matches the site exactly.
const DARK: WaThemeVars = {
  "--wa-header-bg": "var(--admin-panel)",
  "--wa-header-text": "var(--admin-text)",
  "--wa-header-subtext": "var(--admin-muted)",
  "--wa-header-icon": "var(--admin-muted)",
  "--wa-header-hover": "var(--admin-hover)",
  "--wa-header-border": "var(--admin-border)",
  "--wa-wallpaper-bg": "var(--admin-canvas)",
  "--wa-wallpaper-pattern": "none",
  "--wa-bubble-in-bg": "var(--admin-hover)",
  "--wa-bubble-in-text": "var(--admin-text)",
  "--wa-bubble-in-border": "transparent",
  "--wa-bubble-out-bg": "var(--admin-primary)",
  "--wa-bubble-out-text": "#FFFFFF",
  "--wa-bubble-out-border": "transparent",
  "--wa-bubble-meta-text": "var(--admin-muted)",
  "--wa-tick-sent": "var(--admin-muted)",
  "--wa-tick-read": "var(--admin-primary)",
  "--wa-tick-failed": "#F87171",
  "--wa-accent": "var(--admin-primary)",
  "--wa-composer-bg": "var(--admin-panel)",
  "--wa-composer-border": "var(--admin-border)",
  "--wa-composer-field-bg": "var(--admin-hover)",
  "--wa-composer-text": "var(--admin-text)",
  "--wa-composer-placeholder": "var(--admin-muted)",
  "--wa-composer-icon": "var(--admin-muted)",
  "--wa-composer-icon-hover-bg": "var(--admin-hover)",
  "--wa-surface-bg": "var(--admin-panel)",
  "--wa-surface-border": "var(--admin-border)",
  "--wa-surface-text": "var(--admin-text)",
  "--wa-surface-muted-text": "var(--admin-muted)",
  "--wa-surface-hover": "var(--admin-hover)",
  "--wa-highlight-bg": "color-mix(in srgb, var(--admin-primary) 15%, transparent)",
  "--wa-highlight-ring": "color-mix(in srgb, var(--admin-primary) 40%, transparent)",
  "--wa-reply-quote-in-border": "var(--admin-primary)",
  "--wa-reply-quote-in-bg": "var(--admin-hover)",
  "--wa-reply-quote-in-text": "var(--admin-text)",
  "--wa-reply-quote-out-border": "var(--admin-primary)",
  "--wa-reply-quote-out-bg": "var(--admin-hover)",
  "--wa-reply-quote-out-text": "var(--admin-text)",
};

const CLASSIC: WaThemeVars = {
  "--wa-header-bg": "#075E54",
  "--wa-header-text": "#FFFFFF",
  "--wa-header-subtext": "#D9F2EE",
  "--wa-header-icon": "#FFFFFF",
  "--wa-header-hover": "rgba(255,255,255,0.12)",
  "--wa-header-border": "#064E45",
  "--wa-wallpaper-bg": "#E5DDD5",
  "--wa-wallpaper-pattern":
    "repeating-linear-gradient(45deg, rgba(0,0,0,0.035) 0px, rgba(0,0,0,0.035) 1px, transparent 1px, transparent 12px)",
  "--wa-bubble-in-bg": "#FFFFFF",
  "--wa-bubble-in-text": "#111B21",
  "--wa-bubble-in-border": "transparent",
  "--wa-bubble-out-bg": "#DCF8C6",
  "--wa-bubble-out-text": "#111B21",
  "--wa-bubble-out-border": "transparent",
  "--wa-bubble-meta-text": "#667781",
  "--wa-tick-sent": "#667781",
  "--wa-tick-read": "#53BDEB",
  "--wa-tick-failed": "#DC2626",
  "--wa-accent": "#128C7E",
  "--wa-composer-bg": "#F0F0F0",
  "--wa-composer-border": "#D1D7DB",
  "--wa-composer-field-bg": "#FFFFFF",
  "--wa-composer-text": "#111B21",
  "--wa-composer-placeholder": "#667781",
  "--wa-composer-icon": "#54656F",
  "--wa-composer-icon-hover-bg": "#E9EDEF",
  "--wa-surface-bg": "#FFFFFF",
  "--wa-surface-border": "#E5E7EB",
  "--wa-surface-text": "#111827",
  "--wa-surface-muted-text": "#6B7280",
  "--wa-surface-hover": "#F3F4F6",
  "--wa-highlight-bg": "rgba(37,211,102,0.12)",
  "--wa-highlight-ring": "rgba(18,140,126,0.4)",
  "--wa-reply-quote-in-border": "#128C7E",
  "--wa-reply-quote-in-bg": "#F0FDF9",
  "--wa-reply-quote-in-text": "#075E54",
  "--wa-reply-quote-out-border": "#D97706",
  "--wa-reply-quote-out-bg": "#ECFDF5",
  "--wa-reply-quote-out-text": "#B45309",
};

export const WA_THEME_PRESETS: Record<WaThemeId, WaThemeVars> = {
  light: LIGHT,
  dark: DARK,
  classic: CLASSIC,
};
