import {
  dentalGalleryItemsFallback,
  dentalGalleryComparisonsFallback,
  dentalGalleryShowcaseFallback,
  dentalSolutionsFallback,
  dentalTrustFallback,
} from "@/services/dental/fallback";
import type { PortfolioData } from "./types";

const dentalServices: PortfolioData["services"] = [
  { id: "s1", title: "Gingivectomy", title_ar: "", description: "Removes excess gum tissue and reshapes the gum line.", description_ar: "", slug: "gingivectomy", kind: "laser", sort_order: 0, is_published: true, tags: [], image_url: null, media_type: "image", created_at: "", updated_at: "", deleted_at: null },
  { id: "s2", title: "Frenectomy", title_ar: "", description: "Releases abnormal frenum attachments quickly and comfortably.", description_ar: "", slug: "frenectomy", kind: "laser", sort_order: 1, is_published: true, tags: [], image_url: null, media_type: "image", created_at: "", updated_at: "", deleted_at: null },
  { id: "s3", title: "Teeth Whitening", title_ar: "", description: "Removes stains and discoloration for a brighter smile.", description_ar: "", slug: "teeth-whitening", kind: "laser", sort_order: 2, is_published: true, tags: [], image_url: null, media_type: "image", created_at: "", updated_at: "", deleted_at: null },
  { id: "s4", title: "TMJ Pain Therapy", title_ar: "", description: "Relieves pain and inflammation in jaw muscles and TMJ.", description_ar: "", slug: "tmj-pain-therapy", kind: "laser", sort_order: 3, is_published: true, tags: [], image_url: null, media_type: "image", created_at: "", updated_at: "", deleted_at: null },
  { id: "s5", title: "Oral Ulcer Removal", title_ar: "", description: "Relieves pain and promotes faster healing of mouth ulcers.", description_ar: "", slug: "oral-ulcer-removal", kind: "laser", sort_order: 4, is_published: true, tags: [], image_url: null, media_type: "image", created_at: "", updated_at: "", deleted_at: null },
  { id: "s6", title: "Perio Pockets Treatment", title_ar: "", description: "Reduces bacteria and inflammation in periodontal pockets.", description_ar: "", slug: "perio-pockets-treatment", kind: "laser", sort_order: 5, is_published: true, tags: [], image_url: null, media_type: "image", created_at: "", updated_at: "", deleted_at: null },
  { id: "s7", title: "Endodontic Treatment", title_ar: "", description: "Disinfects root canals effectively and supports faster recovery.", description_ar: "", slug: "endodontic-treatment", kind: "our_services", sort_order: 6, is_published: true, tags: [], image_url: null, media_type: "image", created_at: "", updated_at: "", deleted_at: null },
  { id: "s8", title: "Oral Surgeries", title_ar: "", description: "Precise cutting, minimal bleeding, and faster recovery.", description_ar: "", slug: "oral-surgeries", kind: "laser", sort_order: 7, is_published: true, tags: [], image_url: null, media_type: "image", created_at: "", updated_at: "", deleted_at: null },
];

const sliderFeatured: PortfolioData["featured"] = [
  "/dental/771844919_18084846794253727_2495961933820976843_n.jpg",
  "/dental/771892527_18084817961253727_5445355793744516179_n.jpg",
  "/dental/771892527_18084898616253727_5560745852592328857_n.jpg",
  "/dental/771997664_18085564919253727_2931628136836544374_n.jpg",
  "/dental/771998510_18084989687253727_611893741829188574_n.jpg",
].map((url, i) => ({
  id: `slider-${i}`,
  title: `Slider image ${i + 1}`,
  title_ar: "",
  eyebrow: "",
  eyebrow_ar: "",
  slug: null,
  image_url: url,
  media_type: "image" as const,
  sort_order: i,
  is_published: true,
  meta_left: null,
  meta_right: null,
  created_at: "",
  updated_at: "",
  deleted_at: null,
}));

export const portfolioFallback: PortfolioData = {
  settings: {
    id: "fallback",
    brand_name: "The Dental Lounge",
    brand_logo_url: "/dental/766800441_18084577118253727_1449914596899119909_n.jpg",
    footer_tagline: "Modern laser and cosmetic dentistry with comfort-first care in New Cairo.",
    footer_tagline_image_url: null,
    footer_tagline_ar: "",
    contact_email: "",
    contact_email_secondary: "",
    contact_phone: "+20 111 192 2252",
    contact_phone_secondary: "",
    contact_mobile: "+20 111 192 2252",
    contact_address: "A 41 Ozone Medical Center, New Cairo, Al Narges Buildings",
    contact_city: "New Cairo",
    contact_country: "Egypt",
    contact_hours: "",
    contact_map_url: "https://www.google.com/maps/search/?api=1&query=A+41+Ozone+Medical+Center,+New+Cairo,+Al+Narges+Buildings",
    contact_latitude: null,
    contact_longitude: null,
    contact_price_range: "",
    contact_whatsapp: "201111922252",
    contact_telegram: "",
    contact_behance: "",
    contact_linkedin: "",
    contact_instagram: "",
    contact_facebook: "",
    contact_x: "",
    contact_clinic_name: "The Dental Lounge",
    contact_clinic_name_ar: "",
    contact_doctor_name: "Dr / Karim Elshibiny",
    contact_doctor_name_ar: "",
    contact_credentials:
      "Mastership Laser Dentistry - Aachen, Germany\nMembership of American dental association of cosmetic dentistry",
    contact_credentials_ar: "",
    contact_card_image_url:
      "/dental/768432495_18084585374253727_8866675210638190928_n.webp",
    contact_headline: "Book your visit",
    contact_headline_ar: "",
    contact_blurb: "Laser & cosmetic dentistry. Appointments by request.",
    contact_blurb_ar: "",
    case_studies_title: "Smile Results",
    case_studies_title_ar: "",
    case_studies_description: "",
    case_studies_description_ar: "",
    featured_title: "More Images",
    featured_title_ar: "",
    featured_description: "A closer look at the space and care.",
    featured_description_ar: "نظرة أقرب على المكان والرعاية.",
    services_title: "Our Services",
    services_title_ar: "",
    services_description: "",
    services_description_ar: "",
    homepage_section_order: ["about", "services", "gallery", "slider", "contact"],
    homepage_hidden_sections: [],
    about_title: "About Us",
    about_title_ar: "",
    gallery_title: "Successful Cases",
    gallery_title_ar: "حالات ناجحة",
    gallery_heading: "Smile results",
    gallery_heading_ar: "نتائج الابتسامة",
    gallery_description: "Drag to compare before and after.",
    gallery_description_ar: "اسحب للمقارنة بين قبل وبعد.",
    solutions_title: "Comprehensive solutions for the perfect smile",
    solutions_title_ar: "",
    solutions_description:
      "Take a step toward a perfect smile with modern laser technology and personalized care.",
    solutions_description_ar: "",
    services_heading: "Focused treatments with modern technology",
    services_heading_ar: "",
    slider_heading: "Clinic moments",
    slider_heading_ar: "لحظات من العيادة",
    contact_title: "Contact",
    contact_title_ar: "",
    dashboard_layout: [
      { id: "attentionPending", colSpan: 3 },
      { id: "attentionToday", colSpan: 3 },
      { id: "kpiTodayVisits", colSpan: 3 },
      { id: "kpiPending", colSpan: 3 },
      { id: "kpiConfirmedWeek", colSpan: 3 },
      { id: "kpiServices", colSpan: 3 },
      { id: "daySchedule", colSpan: 12 },
      { id: "bookings", colSpan: 3 },
      { id: "recent", colSpan: 3 },
      { id: "schedule", colSpan: 3 },
      { id: "messages", colSpan: 3 },
      { id: "chartVisitsWeek", colSpan: 6 },
      { id: "chartBookingMix", colSpan: 6 },
      { id: "chartStatus", colSpan: 6 },
      { id: "chartBusyHours", colSpan: 6 },
      { id: "chartDayTrend", colSpan: 12 },
    ],
    dashboard_primary_color: "#5E6AD2",
    dashboard_secondary_color: "#3B82F6",
    dashboard_canvas_color: "#F7F8F8",
    dashboard_panel_color: "#FFFFFF",
    created_at: "",
    updated_at: "",
  },
  hero: {
    id: "fallback",
    kicker: "",
    kicker_ar: "",
    headline: "Caring for Your Smile, One Visit at a Time.",
    headline_ar: "",
    accent: "",
    accent_ar: "",
    body: "Your smile is more than just an expression — it's a reflection of your confidence, health, and happiness. At The Dental Lounge, Dr. Karim Elshibiny delivers comfort-first laser and cosmetic care.",
    body_ar: "",
    headline_image_url: null,
    cta_primary_label: "Set Appointment",
    cta_primary_label_ar: "",
    cta_primary_href: "#contact",
    cta_secondary_label: "",
    cta_secondary_label_ar: "",
    cta_secondary_href: "",
    media_type: "image",
    media_url: "/dental/769385837_18084847031253727_8666198053893142707_n.jpg",
    media_url_desktop: "/dental/769385837_18084847031253727_8666198053893142707_n.jpg",
    media_url_mobile: "/dental/769385837_18084847031253727_8666198053893142707_n.jpg",
    created_at: "",
    updated_at: "",
  },
  about: {
    id: "fallback",
    image_url: "/dental/769385837_18084847031253727_8666198053893142707_n.jpg",
    media_type: "image",
    copy_image_url: null,
    copy_media_type: "image",
    drop_cap: "W",
    drop_cap_logo_url: null,
    body: "Under the care of Dr. Karim Elshibiny, The Dental Lounge focuses on modern laser dentistry and cosmetic treatments in a calm, patient-friendly clinic environment.",
    body_ar: "",
    created_at: "",
    updated_at: "",
  },
  callout: null,
  caseStudies: [],
  caseStudySections: {},
  caseStudyDetailPageIds: [],
  featured: sliderFeatured,
  featuredProjectSections: {},
  featuredDetailPageIds: [],
  experience: [],
  services: dentalServices,
  clients: [],
  footerLinks: [
    { id: "f1", label: "About", label_ar: "", href: "#about", sort_order: 0, column_key: "portfolio", display_mode: "text", icon_key: null, icon_url: null, created_at: "", updated_at: "", deleted_at: null },
    { id: "f2", label: "Services", label_ar: "", href: "#services", sort_order: 1, column_key: "portfolio", display_mode: "text", icon_key: null, icon_url: null, created_at: "", updated_at: "", deleted_at: null },
    { id: "f3", label: "Successful Cases", label_ar: "حالات ناجحة", href: "#gallery", sort_order: 2, column_key: "portfolio", display_mode: "text", icon_key: null, icon_url: null, created_at: "", updated_at: "", deleted_at: null },
    { id: "f4", label: "Contact", label_ar: "", href: "#contact", sort_order: 3, column_key: "portfolio", display_mode: "text", icon_key: null, icon_url: null, created_at: "", updated_at: "", deleted_at: null },
  ],
  socialLinks: [],
  trustItems: dentalTrustFallback,
  solutionPanels: dentalSolutionsFallback,
  galleryItems: dentalGalleryItemsFallback,
  galleryShowcase: dentalGalleryShowcaseFallback,
  galleryComparisons: dentalGalleryComparisonsFallback,
};
